# Menu
menu:
  Home: /
  Archives: /archives
  Examples: /examples

# Miscellaneous
favicon: /favicon.ico
brand: /img/hexo.svg

# Ocean Video
ocean:
  path: /img/ocean/
  brand: /img/hexo-inverted.svg

# Content
excerpt_link: 查看全文

search:
  path: search.xml
  filed: post

# Local search
search_text: Search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true
